{{- if .Values.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: "{{ include "bigid-snow.fullname" . }}"
  namespace: {{ $.Release.Namespace | quote }}
  labels:
    {{- include "bigid-snow.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "bigid-snow.selectorLabels" . | nindent 4 }}
{{- end }}
