export APP_VERSION="1.0"
export ORG_NAME="bigexchange"
export CONTAINER_NAME="bigid-snow"
export HOST_NAME="bigid-snow"
export IMAGE_NAME="$ORG_NAME/$CONTAINER_NAME:$APP_VERSION"
export PORTS_HOST="8083"
export PORTS_CONTAINER="8083"